### ISSUE TITLE
Unit test throws errors

### ISSUE THREAD

**Issue by kaihaase-wd** [zefoy/ngx-dropzone-wrapper#23]
Thanks a lot for this nice wrapper. But I'm a little bit in trouble with my unit tests.

The following error occurs in the unit tests of the component that uses the ngx-dropzone-wrapper directive: 
`inline template: 40: 3 caused by: Can not read property 'destroy' of undefined`

This error occurs in Angular 2 and in Angular 4.

Maybe you should check if `this.dropzone` exists before you destroy it in `ngOnDestroy`.

**Comment by sconix** [comment]
I added check for the ngDoCheck so that ngOnDestroy is not called if dropzone has not been initialized yet. This should fix your error, if not then let me know. I released 4.0.1 version so please try that.

**Comment by topa** [comment]
Hi, I'm not sure if this is really related to the original issue here, but I have a strange error spamming my terminal only while running my tests:

> ERROR: 'Error during cleanup of component', UploadComponent{store: Store{_isScalar: false, _dispatcher: Dispatcher{_isScalar: ..., observers: ..., closed: ..., isStopped: ...

This error is caused by a component which uses the DropzoneComponent. I couldn't figure out the issue here. At first I thought there is a `.destroy()` missing, but you've already implemented it.

Do have an idea what I might do wrong?

**Comment by topa** [comment]
<img width="514" alt="bildschirmfoto 2017-04-05 um 15 28 50" src="https://cloud.githubusercontent.com/assets/1116484/24707622/acc02a88-1a14-11e7-9e57-140b7e1f9cbf.png">

I think that causes the error. Setting runInsideAngular might fix the issue.

**Comment by sconix** [comment]
I can't say what could be causing that. I will add unit tests at some point so maybe the issue will present itself to me as well and I could fix it if there is something to fix.
