### ISSUE TITLE
ngx-dropzone + ngIf

### ISSUE THREAD

**Issue by murilobd** [zefoy/ngx-dropzone-wrapper#44]
I'm using ngx-dropzone with Material Tabs. In first tab I have a table and when select an item, goes to 2nd tab where there's a form + dropzone. Everything works fine but, in some cases, I have to hide dropzone in the form (to hide I'm using *ngIf directive. I tried with [hidden] in a parent div but didn't work). When I show up dropzone again, it come back but without the previewTemplate that I had configured. If I try to set the previewTemplate, it doesn't work as well... Any idea how could I solve this issue?! Hide/show dropzone without losing configurations?

**Comment by sconix** [comment]
It should not matter if you use ngIf. The initialization process with ngIf is the same as without it. Are you sure that the previewTemplate is not there just that the styles are off so that its height is 0 etc. Without Plunker example its hard to say what could be the problem. Technically the rendering process with ngIf should be the same as in the first rendering. What do you mean that hidden did not work? If the result was the same then I suspect that you have to have some styling issue.

**Comment by murilobd** [comment]
It was so much simpler than I expected! You told you suspect about styling issue then I went to inspect and the template, after the *ngIF = true, wasn't removing the template from the DOM! Easy stuff!! Thanks again, @sconix !!!
