### ISSUE TITLE
Data not updated on view

### ISSUE THREAD

**Issue by AmitAKB** [zefoy/ngx-dropzone-wrapper#45]
When i tried CSV files on dropzone component CSV updated and i got the result also then this result i putted on this.result variable this result data is not view on html page.

**Comment by sconix** [comment]
This library runs dropzone outside of Angular zone as default. So after setting this.result you need to call markForCheck/detectChanges for Angular to pick up the changes. Or just use [runInsideAngular]="true" as input for the dropzone component/directive. The reason why its false on default is that often onPush is used and you need to anyway call markForCheck/detectChanges on async handlers.

I am going to change this in future versions though so that the outputs are run in Angular zone no matter where the dropzone is run and most likely remove the runInsideAngular at that point since it should not be needed anymore. This will most likely happen with 5.0.0 release when Angular 5 is out.
