### ISSUE TITLE
DropzoneComponent using Dynamic Component Loader

### ISSUE THREAD

**Issue by minuz** [zefoy/ngx-dropzone-wrapper#62]
Hi,

Firstly, thanks for this wrapper! It looks like exactly what I need.
Secondly, I'm trying to use this component within a modal, which I have a wrapper (ngx-bootstrap) and the modal content is dynamic loaded using the Angular dynamic component loader.

The error is as follows.

```
IboxtoolsComponent.html:14 ERROR Error: No component factory found for DropzoneComponent. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (core.js:3789)
    at CodegenComponentFactoryResolver.resolveComponentFactory (core.js:3853)
    at CodegenComponentFactoryResolver.resolveComponentFactory (core.js:3850)
    at CodegenComponentFactoryResolver.resolveComponentFactory (core.js:3850)
    at ComponentLoader._getContentRef (component-loader.class.js:241)
    at ComponentLoader.show (component-loader.class.js:69)
    at BsModalService._showModal (bs-modal.service.js:77)
    at BsModalService.show (bs-modal.service.js:32)
    at WorkItemAttachmentsComponent.initModal (work-item-attachments.component.ts:52)
    at SafeSubscriber.eval [as _next] (work-item-attachments.component.ts:44)
```

At the moment I had to create a wrapper on top of your wrapper to allow me to use this within the modal. Could you please have a look or indicate if there's anything I need to do to implement this correctly?

**Comment by sconix** [comment]
Did you do it as it instructs, added the dropzone component into entrycomponents?

**Comment by minuz** [comment]
yes I did, on the module and on the component that loads that.

**Comment by sconix** [comment]
So what does your wrapper for this wrapper do then that makes it work?

**Comment by minuz** [comment]
Nothing but load your module and your component. Then I provide this module and add my component to EntryComponents and that works for me.
Not sure if it's because it's inside my app or if you put your DropzoneComponent on the entryComponents array inside DropzoneModule will fix this problem. 

I just forked you repo to test it locally but the bundle script is not working for me and unfortunately I won't have time to sort this out as I'm on a really tight deadline.
I might be able to try again later tonight...

**Comment by sconix** [comment]
I don't know how the entryComponent works exactly, but what if you just don't load the dropzone module at all. Instead you import the component / directive from the library and use them in your module.

I'll try to have look how the material components work. Since I think there is a modules that have components that are used as entryComponents.

**Comment by minuz** [comment]
My understanding of the `entryComponents` is that it tells the `ComponentLoaderFactory` (Angular class) that that component can be dynamically injected and when the `FactoryResolver` comes in place, it knows where to find the component.

My assumption is: since the `DropzoneComponent`is not added into your module's `entryComponents` array, when the `FactoryResolver` kicks in, it doesn't know where to get the component. 

However, I don't know if that's how it works for third-party libraries...
Doing that within the application works like a charm, but I'm unsure that simply adding the `DropzoneComponent` into the `DropzoneModule` would work. It's worth a shot though as it is a single line of code change and doesn't really affect the library as the `entryComponents` is only used for the dynamic component loader.

**Comment by sconix** [comment]
Yes, but it feels bit stupid that if every 3rd party lib would need to set all the components to the entryComponents for them to be usable for dynamic loading. So thats why I am hoping that there is some sense in the system and its possible to somehow define the component to be entryComponent in the app module. Anyway I will look into this today and lets see what I find.

**Comment by sconix** [comment]
Ok, so at least with material components the whole dialog is placed into the entryComponents and then the components inside it work normally and they don't need to be in the entryComponents. And this feels to me like it should be. Since to me it does not feel reasonable that the 3rd party libs would place all components that are potentially created dynamically into its entryComponents.

So is the ngx-bootstrap doing it somehow differently like the modal is not dynamically created, instead it only creates the modal content dynamically?

**Comment by minuz** [comment]
Yes, I get it...
It didn't feel right to me as well. 
And yes, ngx-bootsrap allows you to set the content of the model as pure text, a template or a component. When you start the modal inserting a whole component, you need to use a service which uses the dynamic component loader.

I tried to add just the DropzoneComponent into my component entryComponents and inside my module, that didn't work either.
I might need to check on ngx-bootstrap mechanics to see if there's an issue in there. 

This mechanism is also preventing me to use scoped service. Basically the dynamic component loader doesn't find the services provided by the root component, which might be a similar issue, if that makes any sense.

**Comment by sconix** [comment]
Ok, so it is different than what material dialog does. I suspect that it might be working bit differently than how modals are supposed to be used in Angular, but again I am not sure. All I know that defining components as entryComponents in library module does not make sense at least not as long as somebody knows for fact that how it should be with Angular :)

Anyway I think it should work if you just don't use the library module just import and export all the stuff that the library module would in you app module with the dropzone component in entryComponents. At least I don't see how that would not work since it should be the same situation as with you wrapper (i.e. the entry component is handled by the same app module). Of course this is not ideal, but as said I think the problem is how the ngx-bootstrap works.

**Comment by minuz** [comment]
Yes, it might be an issue with ngx-bootstrap. For the time being I'll keep my wrapper around until I have a bit more time to have a deeper look into this. Thanks for your help.
